services:
  node-mcp-server-demo:
    build:
      target: development
    image: node-mcp-server-demo-development
    container_name: node-mcp-server-demo-development
    ports:
      - '3000:3000'
      - '9232:9232'
    links:
      - 'mongodb:mongodb'
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./src/:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
    environment:
      PORT: 3000
      PORT_DEBUG: 9232
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - ai-tech-radar

  mongodb:
    image: mongo:6.0.13
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    networks:
      - ai-tech-radar

volumes:
  mongodb-data:

networks:
  ai-tech-radar:
    name: ai-tech-radar
    driver: bridge

