name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Coverage Directory
        run: mkdir -p -m 777 coverage

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: |
          npm ci
          npm run docker:test

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag node-mcp-server-demo .
          exit $?

      # - name: SonarQubeScan
      #   uses: SonarSource/sonarqube-scan-action@v5.3.1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
